name: Upload artifact to GCS
description: Upload artifact to GCS
inputs:
  platform:
    description: OS and architecture to build for
    required: true

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build_${{ inputs.platform }}
        path: bin/${{ inputs.platform }}
    - name: Upload artifact to GCS
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: bin/${{ inputs.platform }}
        glob: 'pieces_qdrant_server*'
        destination: pieces-libraries/pieces_qdrant_server/${{ github.ref_name }}/${{ inputs.platform }}
        parent: false
