# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. Ok

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_linux:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/rust_build
        with:
          platform: linux

  build_macos_x86_64:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/rust_build
        with:
          platform: macos_x86_64

  build_macos_arm64:
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/rust_build
        with:
          platform: macos_arm64

  build_windows:
    runs-on: windows-latest-16-cores
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/rust_build
        with:
          platform: windows

  gcloud_release:
    runs-on: ubuntu-latest
    needs:
      - build_linux
      - build_macos_x86_64
      - build_macos_arm64
      - build_windows

    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with Google cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.PIECES_GCLOUD_SERVICE_KEY }}
          project_id: pi3c3s-cloud-server
          create_credentials_file: true

      - name: 'Upload to GCS - linux'
        uses: ./.github/actions/gcs_upload
        with:
          platform: linux
      - name: 'Upload to GCS - macos_x86_64'
        uses: ./.github/actions/gcs_upload
        with:
          platform: macos_x86_64
      - name: 'Upload to GCS - macos_arm64'
        uses: ./.github/actions/gcs_upload
        with:
          platform: macos_arm64
      - name: 'Upload to GCS - windows'
        uses: ./.github/actions/gcs_upload
        with:
          platform: windows